### ISSUE TITLE
Description panel doesn't properly display hyperlink in item description

### ISSUE THREAD

**Issue by oevans** [Esri/swipe-map-storytelling-template-js#12]
See this example [app](http://www.arcgis.com/apps/StorytellingSwipe/index.html?appid=bd385749fa2347ad915425e6c9b6f2db&webmap=0127099bf9054d80b584e2501c7809a1) and notice how the URL is written out in the description panel.

However, if you look at the [item](http://www.arcgis.com/home/item.html?id=bd385749fa2347ad915425e6c9b6f2db) the URL in the item description is configured as a hyperlink.

![screen shot 2014-06-06 at 7 48 02 am](https://cloud.githubusercontent.com/assets/3215530/3199820/727a1e98-ed70-11e3-8aff-2a0becb50773.png)

**Comment by glazou** [comment]
The Swipe app populate the panel with the content of the item description when saving the story for the first time but those are not kept in sync after. This is not a common workflow for creating the story anymore, we will leave the ability for the author to edit markup not properly imported.
