### ISSUE TITLE
No index.html?

### ISSUE THREAD

**Issue by upcamogie** [Esri/swipe-map-storytelling-template-js#16]
I downloaded the zip file but I do not see the Index.html file.....where should I be looking for this? the instructions seem to indicate this file should be in the main folder not buried somewhere. thanks

**Comment by cooney** [comment]
Which version did you download?  User or Developer?  If User, then it is located in the parent folder.  If Developer, then it is located in the Swipe/src folder.

**Comment by upcamogie** [comment]
whatever the link to the download was, I think developer. i DLed again and its there, i dont think whole contents copied to my new location when i unzipped. Where is the user version? Does that allow any custom tweaks? I am not a developer by any means but I like to change colors & add logos, etc. thx

**Comment by cooney** [comment]
If its titled 'Storytelling-Swipe-1.4.4' then its User, if its 'swipe-map-storytelling-template-js-master' then its Developer.  If you just wanted to change some styles with css, the User download is sufficient and your customization could be added to the index.html.
