### ISSUE TITLE
does it matter what type of service/layers you use?

### ISSUE THREAD

**Issue by upcamogie** [Esri/swipe-map-storytelling-template-js#17]
i want to swipe a single web map. i have 2 layers in there (added as feature layers). i am following the help:
"If you are choosing to swipe between layers of a single webmap, enter your web map ID and optionally edit the layerIndex property to select the layer to be revealed. By default the top layer will be used."

it doesnt matter what # i put for layer index, 0 or 1, the same layer always appears in both views. do both layers need to be turned on/off in the web map? the help is not clear on any details on how the web and layers need to be set

and BTW, is this forum appropriate to ask these questions? Almost always my questions are because the readme files are so sparse and not clear. so i think its appropriate but perhaps not

**Comment by cooney** [comment]
Appears to be a bug in the download (works in the ArcGIS Online hosted version).  Are you able to use the AGOL hosted version of the application for your project?  I will investigate this issue in the meantime.

**Comment by cooney** [comment]
Fixed and updated.  See here for latest release and download: https://github.com/Esri/swipe-map-storytelling-template-js/releases/tag/V1.4.4.1

**Comment by upcamogie** [comment]
map looks good now, layers are displaying as expected. thanks for the fast fix. Is it possible to change the position of the divider/swipe bar or its thickness?

**Comment by cooney** [comment]
Yep, you would simply have to modify the css width property for the swipe bar (can be found in the class called 'moveable').  As for the position, you would have to modify the JavaScript in the developer's download.  The line to modify in MapSwipe.js can be found at line 142 (look for sliderDiv.node.style.left).

And feel free to post questions and comments like this over on our community forum where it will probably get more attention from our entire community. (https://geonet.esri.com/community/gis/web-gis/storymaps/content)

Cheers
