### ISSUE TITLE
Using custom locator

### ISSUE THREAD

**Issue by mpboyle** [Esri/swipe-map-storytelling-template-js#18]
I'm wondering what needs to be done to use a custom locator, not the default Esri one?  I put in the REST endpoint of a locator in the commonConfig.js file, but the Esri locator is still being used.

**Comment by glazou** [comment]
Sorry about this, the value defined in the config file is always overwritten by the geocoder default URL provided by ArcGIS Online. 

Until we fix this, your best option is to follow the developer guide https://github.com/Esri/swipe-map-storytelling-template-js#developer-guide and comment the following block of code https://github.com/Esri/swipe-map-storytelling-template-js/blob/master/Swipe/src/app/storymaps/core/Core.js#L243 . Then the value you define in commonConfig will be used.

Note that if you have an Organization membership, you can configure a custom geocoder through the settings. Note that only the first one in the list of geocoders will be used.

![image](https://cloud.githubusercontent.com/assets/994078/7967469/20520662-09df-11e5-8f9a-06feefbe4e07.png)
