### ISSUE TITLE
Extra margin above description when loading the first time in embed mode

### ISSUE THREAD

**Issue by ssylvia** [Esri/swipe-map-storytelling-template-js#19]
toggling the description's visibility solves this problem, but it is not correct when first loaded.

![screen shot 2015-04-06 at 10 51 47 am](https://cloud.githubusercontent.com/assets/1211360/7005997/7a555068-dc4b-11e4-98b1-90f1d5ff45fa.png)

**Comment by cooney** [comment]
Resolved with 1.5
