### ISSUE TITLE
Spin.min and IE 9

### ISSUE THREAD

**Issue by jenniferhiggs** [Esri/swipe-map-storytelling-template-js#20]
The page will not load in IE 9.  We get the following error in Spin.min

spin.min.js?v=1.4.3&_=1428616895060, line 2 character 1070

**Comment by glazou** [comment]
We looked into this and have been able to reproduce the issue with the developer version of the Swipe template and IE9. We are not going to be able to fix that issue but this should not affect you too much as in fact that you are using is intended for development only. 

Swipe comes in two version:
 - user download http://links.esri.com/storymaps/swipe_template_zip (not intended for customization or css customization)
 - developer download https://github.com/Esri/swipe-map-storytelling-template-js/archive/master.zip (intended for deep customization)

If you have made customization to the application, when deploying production application, you should follow the procedure here https://github.com/Esri/swipe-map-storytelling-template-js#developer-guide to create a production version that won't be affected by this issue.

If you have note made any customization to your shortlist or a customization that does not require deep modification of the Javascript, you should be using the developer download that won't have this issue http://links.esri.com/storymaps/swipe_template_zip
