### ISSUE TITLE
Popup not showing on mobile interface

### ISSUE THREAD

**Issue by darkbluemsu** [Esri/swipe-map-storytelling-template-js#23]
Is it by design? If so, would it be a good idea to support it in the future? Thanks

**Comment by cooney** [comment]
The popup information is displayed in its own panel on smaller/mobile screens.  Look for the 'Data' tab at the top of the screen.
![swipe mobile popup 2](https://cloud.githubusercontent.com/assets/1232180/18135964/8f76eea6-6f58-11e6-9d77-cb9eb6cf50b7.png)
